apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "cfXx/cQBTHPwnrwrsKPoqygIh5534TT+mt0DN+Juqns571+Ma3BNuOJzY3H5NvJd\nj5TaLiEiN0o7iDjVmCecUZ43VOZsghGYnep0VxGKmAQvYvrVopo7nVaG2MG9wSDq\nbb+fKN/k9DzpMIx6jOH5Wb+THivRLqQBPZ2S1bMwueM="
