apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "G/nWrZt5NX3dUT/Ip+GRasejj/TftV/Y+eJWgXxbqzA+940Mon3L7FS9r9BCbv1y\n5XDKAWmzw7QbT9D1X8RfCbqyCag0k6J3I3GvWic+Ty+A3WoGYsT7YPYA3g95VTMn\n+L2fd4n4Bn1KGXlx60/YkGTEOtu3fHBxGqDsTWelFxo="
